# Generated by Django 5.0.7 on 2024-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesignal', '0002_alter_historicaldata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
